version: "3.9"
services:
  db:
    image: mysql:latest
    container_name: base_datos
    environment:
      - MYSQL_DATABASE=taller
      - MYSQL_ROOT_PASSWORD=12345
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db-dump:/docker-entrypoint-initdb.d
    networks:
      - dto-red

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
    networks:
      - dto-red

  web-datos:
    container_name: servidor-web
    build:
      context: .
      dockerfile: ./datos/Dockerfile
    volumes:
      - ./datos/src:/var/www/html/src
      - ./datos/public:/var/www/html/public
    ports:
      - 8000:80
    depends_on:
      - db
    networks:
      - dto-red

  web-negocio:
    container_name: servidor-negocio
    build:
      context: .
      dockerfile: ./negocio/Dockerfile
    volumes:
      - ./negocio/src:/var/www/html/src
      - ./negocio/public:/var/www/html/public
    ports:
      - 9000:80
    depends_on:
      - web-datos
    networks:
      - dto-red

secrets:
  db_password:
    file: db_password.txt

volumes:
  db-dump:
  mysql:
  www:
  negocio:

networks:
  dto-red:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
